//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nogales.BusinessModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NogalesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NogalesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nogales.BusinessModel.NogalesResources", typeof(NogalesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;TotalCasesSold&quot;:{&quot;Grocery&quot;:null,&quot;Produce&quot;:null,&quot;All&quot;:[{&quot;SubData&quot;:[{&quot;SubData&quot;:null,&quot;GroupName&quot;:&quot;HUHE&quot;,&quot;Label1&quot;:&quot;Jan Apr 18&quot;,&quot;cValue1&quot;:429.02,&quot;rValue1&quot;:10454.75,&quot;Color1&quot;:&quot;#00a2ed&quot;,&quot;SalesPerson1&quot;:&quot;&quot;,&quot;Period1&quot;:&quot;\/Date(1523298599000)\/&quot;,&quot;Label2&quot;:&quot;Jan Apr 18&quot;,&quot;cValue2&quot;:0,&quot;rValue2&quot;:0,&quot;Color2&quot;:&quot;#0ab0fd&quot;,&quot;SalesPerson2&quot;:&quot;&quot;,&quot;Period2&quot;:&quot;\/Date(1523298599000)\/&quot;,&quot;Label3&quot;:&quot;Jan Apr 17&quot;,&quot;Label4&quot;:&quot;Jan Apr 17&quot;,&quot;Label5&quot;:&quot;&quot;,&quot;Label6&quot;:&quot;&quot;,&quot;cValue3&quot;:0,&quot;cValue4&quot;:0,&quot;cValue5&quot;:0,&quot;cValue6&quot;:0,&quot;rValue3&quot;:0,&quot;rValue4&quot;:0,&quot;rValue5&quot;:0,&quot;rValue [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomerServiceGraph {
            get {
                return ResourceManager.GetString("CustomerServiceGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ListSalesPerson&quot;:null,&quot;SalesPerson&quot;:null,&quot;AssignedPersonCode&quot;:null,&quot;Customer&quot;:&quot;FARNER-BOCKEN COMPANY              &quot;,&quot;CustomerNumber&quot;:&quot;FAR004&quot;,&quot;SalesAmount&quot;:null,&quot;Type&quot;:null,&quot;NoOfCustomer&quot;:0,&quot;SalesQty&quot;:7859.00,&quot;SalesAmountCurrent&quot;:134991.25,&quot;SalesAmountPrior&quot;:293539.40,&quot;Percentage&quot;:-54.012500,&quot;SalesPersonDescription&quot;:null,&quot;Difference&quot;:-158548.15,&quot;Binno&quot;:null,&quot;Picker&quot;:null,&quot;Commodity&quot;:null,&quot;CasesSoldPrior&quot;:17871.00,&quot;CasesSoldCurrent&quot;:7859.00,&quot;DifferenceCasesSold&quot;:-10012.00,&quot;PercentageCasesSold&quot;:-56.023700} [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomerServiceReport {
            get {
                return ResourceManager.GetString("CustomerServiceReport", resourceCulture);
            }
        }
    }
}
