// <auto-generated />
namespace Nogales.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ForceReset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForceReset));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151001439_ForceReset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
